#!/usr/bin/env python3

import argparse
import shutil
import subprocess
from pathlib import Path

parser = argparse.ArgumentParser(prog="testrun")
parser.add_argument("--mpirun", type=Path)
parser.add_argument("--pot3d", type=Path)
parser.add_argument("--testsuite", type=Path)
parser.add_argument("--workdir", type=Path)
args = parser.parse_args()

shutil.copytree(args.testsuite / "input", args.workdir, dirs_exist_ok=True)
subprocess.run(
    [
        args.mpirun,
        "--mca",
        "btl",
        "tcp,self",
        "--mca",
        "btl_tcp_if_include",
        "lo",
        "--oversubscribe",
        "-np",
        "12",
        args.pot3d,
    ],
    cwd=args.workdir,
    check=True,
)

with open(args.workdir / "pot3d.out") as f:
    test = f.readlines()[-4:]

with open(args.testsuite / "validation/pot3d.out") as f:
    ref = f.readlines()[-4:]

assert test == ref
